language: java
branches:
  only:
    - develop
    - /^release-[0-999].[0-999]$/
    - master
notifications:
  email:
    recipients:
      - Sonia.bejar017@gmail.com

script:
  #Test unitario y de integracion con cobertura (jacoco)
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify

  #SONARCLOUD
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=soniabm -Dsonar.login=$SONAR

#Deploy https://iwvg-ecosystem.herokuapp.com/api
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU
  on:
    branch: master
  app: iwvg-ecosystem-sonia-bejar

